Repository venus-lion/movlit-plus, pull requests merged in 2025-02, with the labels that each got.

#71 [be, fe] 회원 프로필 조회, 영화 상세페이지 코멘트와 프로필 연결 완료
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/member/infra/persistence/jpa/MemberJpaRepository.java
  be/src/main/java/movlit/be/member/presentation/MemberController.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieCommentJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/MovieDetailReadController.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieCommentReadResponse.java
  fe/src/components/MemberProfilePage.css
  fe/src/components/MemberProfilePage.jsx
  fe/src/components/MovieDetailPage.css
  fe/src/components/MovieDetailPage.jsx
  fe/src/main.jsx
Labels: feat

#72 [be, fe] 도서 상세페이지 코멘트에서 회원 프로필로 이동할 수 있도록 구현
  be/src/main/java/movlit/be/book/infra/persistence/jpa/BookCommentJpaRepository.java
  be/src/main/java/movlit/be/book/presentation/dto/BookCommentResponseDto.java
  fe/src/components/BookDetailPage.css
  fe/src/components/BookDetailPage.jsx
Labels: feat

#74 [fe] 코멘트 유저와 로그인 유저가 같다면 마이페이지로 이동
  fe/src/components/BookDetailPage.jsx
  fe/src/components/MovieDetailPage.jsx
Labels: fix

#75 [fe] 알림 관련 잡다한 기능 추가
  fe/src/App.jsx
  fe/src/PrivateRoute.jsx
  fe/src/images/notification.jpg
  fe/src/main.jsx
Labels: feat

#76 be/feat/#63-group-chatroom-notification
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/image/application/service/ImageService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/FetchGroupChatroomUseCase.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/GroupChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/ProfileImageUpdatedEventListener.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/controller/GroupChatroomController.java
  be/src/main/java/movlit/be/pub_sub/notification/NotificationController.java
  be/src/main/java/movlit/be/pub_sub/notification/NotificationMessage.java
  be/src/main/java/movlit/be/pub_sub/notification/NotificationService.java
  fe/package-lock.json
  fe/src/hooks/useSSE.jsx
Labels: feat, fix

#78 [be, fe] notification url 추가
  be/src/main/java/movlit/be/follow/application/service/FollowWriteService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/GroupChatroomService.java
  be/src/main/java/movlit/be/pub_sub/notification/NotificationDto.java
  fe/src/App.jsx
  fe/src/components/chat/Chat.jsx
  fe/src/main.jsx
Labels: feat, fix

#86 [be] 일대일 채팅 중복 생성 해결
  be/src/main/java/movlit/be/common/exception/ErrorMessage.java
  be/src/main/java/movlit/be/common/exception/OneOnOneChatroomAlreadyExistsException.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/OneononeChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/repository/OneononeChatroomRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/OneononeChatroomRepositoryImpl.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/jpa/OneononeChatroomJpaRepository.java
  be/src/test/java/movlit/be/acceptance/oneonone_chatroom/OneOnOneChatroomSteps.java
  be/src/test/java/movlit/be/acceptance/oneonone_chatroom/OneononeChatroomTest.java
Labels: refactor, fix

#92 [be] 스레드 재설정
  be/src/main/java/movlit/be/common/config/AppConfig.java
  be/src/main/java/movlit/be/pub_sub/RedisNotificationSubscriber.java
  be/src/main/java/movlit/be/pub_sub/notification/SseEmitterService.java
Labels: fix

#99 [be] oauth 중간 pr
  be/src/main/java/movlit/be/auth/application/service/MyMemberDetails.java
  be/src/main/java/movlit/be/auth/application/service/MyOAuth2MemberService.java
  be/src/main/java/movlit/be/auth/application/service/OAuth2AuthenticationSuccessHandler.java
  be/src/main/java/movlit/be/auth/domain/repository/AuthCodeStorage.java
  be/src/main/java/movlit/be/auth/infra/persistence/ConcurrentAuthCodeStorage.java
  be/src/main/java/movlit/be/auth/presentation/AuthenticationController.java
  fe/src/OAuthCallback.jsx
  fe/src/axiosInstance.js
Labels: feat, fix

#100 [be] oauth2 해결인가?
  be/src/main/java/movlit/be/auth/application/service/MyMemberDetails.java
  be/src/main/java/movlit/be/auth/application/service/MyOAuth2MemberService.java
  be/src/main/java/movlit/be/auth/presentation/AuthenticationController.java
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/member/application/converter/MemberConverter.java
  be/src/main/java/movlit/be/member/application/service/MemberWriteService.java
Labels: fix

#102 [be] OAuth2 로그인 시, 헤더 들어오도록 변경
  be/src/main/java/movlit/be/auth/application/service/MyOAuth2MemberService.java
  be/src/main/java/movlit/be/auth/application/service/OAuth2AuthenticationSuccessHandler.java
  be/src/main/java/movlit/be/auth/presentation/AuthenticationController.java
  be/src/main/java/movlit/be/common/filter/JwtRequestFilter.java
Labels: feat, fix

#104 OAuth, 토스트 알림창 수정
  be/src/main/java/movlit/be/auth/application/service/CustomArgumentResolver.java
  be/src/main/java/movlit/be/auth/application/service/MyMemberDetails.java
  be/src/main/java/movlit/be/auth/application/service/MyOAuth2MemberService.java
  be/src/main/java/movlit/be/auth/application/service/OAuth2AuthenticationSuccessHandler.java
  be/src/main/java/movlit/be/auth/domain/repository/AuthCodeStorage.java
  be/src/main/java/movlit/be/auth/infra/persistence/ConcurrentAuthCodeStorage.java
  be/src/main/java/movlit/be/auth/presentation/AuthenticationController.java
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/common/config/WebConfig.java
  be/src/main/java/movlit/be/common/filter/JwtRequestFilter.java
  be/src/main/java/movlit/be/member/application/converter/MemberConverter.java
  be/src/main/java/movlit/be/member/application/service/MemberWriteService.java
  fe/src/App.jsx
  fe/src/OAuthCallback.jsx
  fe/src/axiosInstance.js
  fe/src/components/MemberProfilePage.jsx
  fe/src/components/MovieDetailPage.jsx
  fe/src/components/MyPage.jsx
  fe/src/components/chat/ChatList.jsx
  fe/src/components/chat/CreateGroupChatModal.jsx
  fe/src/components/chat/CreateGroupChatNameModal.jsx
  fe/src/pages/ChatPage.jsx
  fe/src/pages/ChatPageGroup.jsx
  fe/src/pages/MemberLogin.jsx
  fe/src/pages/MemberRegister.jsx
Labels: feat, fix

#105 배포 수정
  .github/workflows/be-cd.yml
  be/src/main/java/movlit/be/auth/application/service/MyMemberDetails.java
Labels: fix

#106 [fe] 채팅방 리스트 pub 설정 + 토스트 알림창 수정
  be/src/main/java/movlit/be/common/config/RedisStreamConfig.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/FetchMyOneononeChatroomUseCase.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/OneononeChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/controller/GroupChatroomController.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/controller/OneononeChatroomController.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/dto/OneononeChatroomResponse.java
  fe/src/App.jsx
  fe/src/components/chat/Chat.jsx
  fe/src/components/chat/ChatList.jsx
  fe/src/components/chat/CreateGroupChatNameModal.jsx
  fe/src/util/ChatMessageDatetime.jsx
Labels: feat, fix

#107 [fe] 프론트쪽 설정 추가
  fe/src/components/MemberProfilePage.jsx
  fe/src/components/MovieDetailPage.jsx
  fe/src/components/MyPage.jsx
  fe/src/pages/MemberLogin.jsx
  fe/src/pages/MemberRegister.jsx
Labels: feat, fix

#108 Fix(fe) Toast 수정
  fe/src/assets/css/main.css
Labels: fix

#111 Fix(fe) 그룹채팅 / 개인채팅 split 문제 해결
  fe/src/components/chat/ChatList.jsx
  fe/src/pages/ChatPage.jsx
  fe/src/util/ChatMessageDatetime.jsx
Labels: fix

#114 [fe] 전역 css 파일 import문 추가
  be/src/main/java/movlit/be/pub_sub/chatMessage/presentation/dto/response/ChatMessageDto.java
  fe/package-lock.json
  fe/package.json
  fe/src/components/chat/ChatList.jsx
  fe/src/main.jsx
  fe/src/pages/ChatPage.jsx
  fe/src/pages/ChatPageGroup.jsx
  fe/src/util/DateTimeUtil.jsx
Labels: feat

#116 [fe] css 문제 없는 Material-UI 사용하도록 변경
  be/src/main/java/movlit/be/common/config/TomcatWebCustomConfig.java
  fe/package-lock.json
  fe/package.json
  fe/src/App.jsx
  fe/src/assets/css/main.css
  fe/src/components/MemberProfilePage.jsx
  fe/src/components/MovieDetailPage.jsx
  fe/src/components/MyPage.jsx
  fe/src/components/chat/Chat.jsx
  fe/src/components/chat/CreateGroupChatModal.jsx
  fe/src/components/chat/CreateGroupChatNameModal.jsx
  fe/src/main.jsx
  fe/src/pages/FollowToggleButton.jsx
  fe/src/pages/MemberLogin.jsx
  fe/src/pages/MemberRegister.jsx
Labels: fix

#117 be/feat/#113-oneononeChatroom-create
  be/src/main/java/movlit/be/auth/application/service/MyMemberDetails.java
  be/src/main/java/movlit/be/auth/application/service/OAuth2AuthenticationSuccessHandler.java
  be/src/main/java/movlit/be/auth/presentation/AuthenticationController.java
  be/src/main/java/movlit/be/common/filter/JwtRequestFilter.java
  be/src/main/java/movlit/be/pub_sub/RedisListenerConfig.java
  be/src/main/java/movlit/be/pub_sub/RedisMessagePublisher.java
  be/src/main/java/movlit/be/pub_sub/RedisMessageSubscriber.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/OneononeChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/controller/OneononeChatroomController.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/dto/OneononeChatroomCreatePubDto.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/dto/OneononeChatroomCreatePubRequest.java
  fe/src/components/chat/Chat.jsx
  fe/src/components/chat/ChatList.jsx
  fe/src/pages/ChatPage.jsx
Labels: feat, fix

#126 배포
  .github/workflows/be-cd.yml
  be/src/main/java/movlit/be/book/application/service/BookHeartReadService.java
  be/src/main/java/movlit/be/book/application/service/BooksRecommendationService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageService.java
  fe/index.html
  fe/src/assets/css/loading.css
  fe/src/assets/css/main.css
  fe/src/assets/js/main.js
  fe/src/components/BookDetailPage.css
  fe/src/components/BookDetailPage.jsx
  fe/src/components/MovieDetailPage.jsx
  fe/src/components/MyPage.css
  fe/src/components/MyPage.jsx
  fe/src/components/chat/Chat.jsx
  fe/src/components/chat/ChatList.jsx
  fe/src/components/chat/ChatTabHover.css
  fe/src/components/chat/ChatTabs.jsx
  fe/src/components/chat/CreateGroupChatModal.jsx
  fe/src/main.jsx
  fe/src/pages/BestsellerBooksComponent.jsx
  fe/src/pages/BookCarousel.jsx
  fe/src/pages/BookCarouselRecommend.jsx
  fe/src/pages/BookGenreCarousel.jsx
  fe/src/pages/BookSearchDetailPage.jsx
  fe/src/pages/GenreMoviesComponent.jsx
  fe/src/pages/Home.css
  fe/src/pages/InterestGenreMoviesComponent.jsx
  fe/src/pages/LatestMoviesComponent.jsx
  fe/src/pages/MovieCarousel.jsx
  fe/src/pages/MovieHome.jsx
  fe/src/pages/MovieSearchDetailPage.jsx
  fe/src/pages/NewBooksComponent.jsx
  fe/src/pages/PopularBooksComponent.jsx
  fe/src/pages/PopularMoviesComponent.jsx
  fe/src/pages/RandomGenreBooksComponent.jsx
  fe/src/pages/RecentHeartSimilarCrewMoviesComponent.jsx
  fe/src/pages/UserRecommendationComponent.jsx
Labels: fix

#138 be/refactor/update-profile
  be/src/main/java/movlit/be/chat_room/application/service/FetchOneononeChatroomUseCase.java
  be/src/main/java/movlit/be/chat_room/application/service/GroupChatroomJoinedEventListener.java
  be/src/main/java/movlit/be/chat_room/application/service/GroupChatroomLeaveEventListener.java
  be/src/main/java/movlit/be/chat_room/application/service/OneononeChatroomService.java
  be/src/main/java/movlit/be/chat_room/application/service/ProfileImageUpdatedEventListener.java
  be/src/main/java/movlit/be/chat_room/presentation/controller/OneononeChatroomController.java
  be/src/main/java/movlit/be/chat_room/presentation/dto/OneononeChatroomResponse.java
  be/src/main/java/movlit/be/chat_room/presentation/dto/UpdateRoomDto.java
  be/src/main/java/movlit/be/common/config/RedisMessageSubscriber.java
  fe/src/pages/ChatPage.jsx
  fe/src/pages/ChatPageGroup.jsx
Labels: feat, refactor

#169 Hotfix(fe) 채팅메시지
  fe/src/components/chat/Chat.jsx
  fe/src/pages/ChatPage.jsx
  fe/src/pages/ChatPageGroup.jsx
Labels: hot fix
