Repository venus-lion/movlit-plus, pull requests merged in 2025-01, with the labels that each got.

#1 Feat(be). Redis Pub/Sub 채팅 기능 초안
  be/build.gradle
  be/src/main/java/movlit/be/pub_sub/ChatController.java
  be/src/main/java/movlit/be/pub_sub/ChatReadController.java
  be/src/main/java/movlit/be/pub_sub/ChatService.java
  be/src/main/java/movlit/be/pub_sub/MessageController.java
  be/src/main/java/movlit/be/pub_sub/RedisConfig.java
  be/src/main/java/movlit/be/pub_sub/RedisMessagePublisher.java
  be/src/main/java/movlit/be/pub_sub/RedisMessageSubscriber.java
  be/src/main/java/movlit/be/pub_sub/RedisPubSubConfig.java
  be/src/main/java/movlit/be/pub_sub/StompInterceptor.java
  be/src/main/java/movlit/be/pub_sub/WebSocketConfig.java
  be/src/main/java/movlit/be/pub_sub/dto/response/ChatMessage.java
Labels: enhancement

#3 Feat(be). Redis Pub/Sub 채팅 기능 초안3
  be/src/main/java/movlit/be/pub_sub/RedisConfig.java
  be/src/main/java/movlit/be/pub_sub/RedisPubSubConfig.java
  be/src/main/java/movlit/be/pub_sub/chat/application/service/ChatRoomService.java
  be/src/main/java/movlit/be/pub_sub/entity/ChatRoom.java
Labels: enhancement

#22 [be] Member와 GroupChatroom 연관관계 재매핑
  be/src/main/java/movlit/be/member/domain/entity/MemberEntity.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/convertor/ChatroomConvertor.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/GroupChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/GroupChatroom.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/MemberRChatroom.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/repository/GroupChatRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/GroupChatRepositoryImpl.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/jpa/GroupChatroomJpaRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/controller/ChatroomReadController.java
Labels: hot fix

#25 Feat(fe) 그룹채팅방 생성 모달 1,2 완료
  fe/src/assets/css/CreateGroupChatModal.css
  fe/src/assets/css/CreateGroupChatNameModal.css
  fe/src/components/chat/Chat.jsx
  fe/src/components/chat/CreateGroupChatModal.jsx
  fe/src/components/chat/CreateGroupChatNameModal.jsx
Labels: feat

#28 Feat(be) 일대일 채팅방 시작
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/common/util/ids/MemberROneOnOneChatroomId.java
  be/src/main/java/movlit/be/common/util/ids/OneOnOneChatroomId.java
  be/src/main/java/movlit/be/member/domain/entity/MemberEntity.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/OneOnOneChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/MemberROneOnOneChatroom.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/OneOnOneChatRoom.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/ParticipantIds.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/jpa/OneOnOneChatroomJpaRepository.java
  fe/src/components/chat/CreateGroupChatNameModal.jsx
Labels: feat

#32 [be] 그룹 채팅 API 구현 및 1:1 채팅 리팩토링
  be/src/main/java/movlit/be/pub_sub/RedisMessageSubscriber.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageBatchService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/domain/ChatMessage.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/infra/persistence/mongo/ChatMessageMongoRepository.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/presentation/ChatMessageWriteController.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/presentation/dto/response/ChatMessageDto.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/presentation/dto/response/MessageType.java
  fe/src/pages/ChatPage.jsx
Labels: feat, refactor

#35 [be] 그룹 채팅 API 구현
  be/src/main/java/movlit/be/pub_sub/RedisMessagePublisher.java
  be/src/main/java/movlit/be/pub_sub/RedisMessageSubscriber.java
Labels: feat

#38 be/feat/#11-Create-GroupChatroom-API
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/movlit/be/common/exception/ErrorMessage.java
  be/src/main/java/movlit/be/common/exception/FailedDeserializeException.java
  be/src/main/java/movlit/be/common/util/IdFactory.java
  be/src/main/java/movlit/be/common/util/ids/OneononeChatroomId.java
  be/src/main/java/movlit/be/member/domain/entity/MemberEntity.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/domain/ChatMessage.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/OneOnOneChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/OneononeChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/MemberROneononeChatroom.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/OneOnOneChatroom.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/repository/OneononeChatroomRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/OneononeChatroomRepositoryImpl.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/jpa/MemberROneononeChatroomJpaRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/jpa/OneOnOneChatroomJpaRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/jpa/OneononeChatroomJpaRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/controller/OneononeChatroomController.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/dto/OneononeChatroomRequest.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/dto/OneononeChatroomResponse.java
  be/src/test/java/movlit/be/acceptance/oneonone_chatroom/OneOnOneChatroomSteps.java
  be/src/test/java/movlit/be/acceptance/oneonone_chatroom/OneononeChatroomTest.java
Labels: feat

#49 Feat(be) 토픽 2개 추가, 읽음처리 관련 로직 추가
  be/src/main/java/movlit/be/pub_sub/RedisConfig.java
  be/src/main/java/movlit/be/pub_sub/RedisMessagePublisher.java
  be/src/main/java/movlit/be/pub_sub/RedisMessageSubscriber.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/domain/ChatMessage.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/infra/persistence/ChatMessageRepository.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/infra/persistence/ChatMessageRepositoryImpl.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/infra/persistence/mongo/ChatMessageMongoRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/dto/UpdateRoomDto.java
  be/src/test/java/movlit/be/ChatMessage/application/service/ChatMessageServiceTest.java
Labels: feat

#51 [be] Redis Queue를 활용하여 채팅방 생성 동시성 문제 해결
  be/src/main/java/movlit/be/common/exception/ErrorMessage.java
  be/src/main/java/movlit/be/common/exception/GroupChatroomAlreadyExistsException.java
  be/src/main/java/movlit/be/common/exception/GroupChatroomCreationWhenWorkingException.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/convertor/ChatroomConvertor.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/GroupChatroomCreationWorker.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/GroupChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/dto/RequestDataForCreationWorker.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/repository/GroupChatRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/GroupChatRepositoryImpl.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/jpa/GroupChatroomJpaRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/controller/GroupChatroomController.java
Labels: feat

#57 [be] 그룹 채팅 오류 해결과 리팩토링
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/data_collection/movie/MovieCollectController.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/infra/persistence/ChatMessageRepository.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/infra/persistence/ChatMessageRepositoryImpl.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/infra/persistence/mongo/ChatMessageMongoRepository.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/presentation/ChatMessageReadController.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/GroupChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/repository/GroupChatRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/GroupChatRepositoryImpl.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/presentation/controller/GroupChatroomController.java
  fe/src/components/chat/Chat.jsx
  fe/src/components/chat/ChatList.jsx
Labels: feat, refactor, fix

#62 Fix(be) 채팅 메시지 Redis Stream Publish/Consume 처리
  be/src/main/java/movlit/be/common/config/RedisStreamConfig.java
  be/src/main/java/movlit/be/common/exception/ErrorMessage.java
  be/src/main/java/movlit/be/common/exception/RedisStreamOperationReturnNull.java
  be/src/main/java/movlit/be/pub_sub/RedisConfig.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageConsumer.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageStreamListener.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/domain/ChatMessage.java
  be/src/test/java/movlit/be/ChatMessage/application/service/ChatMessageWriteServiceTest.java
Labels: feat, fix

#64 [be] SSE 일대일 채팅 알림 구현 완료
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/pub_sub/RedisNotificationSubscriber.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/application/service/ChatMessageService.java
  be/src/main/java/movlit/be/pub_sub/chatMessage/presentation/ChatMessageWriteController.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/application/service/OneononeChatroomService.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/domain/repository/OneononeChatroomRepository.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/OneononeChatroomRepositoryImpl.java
  be/src/main/java/movlit/be/pub_sub/chatRoom/infra/persistence/jpa/OneononeChatroomJpaRepository.java
  be/src/main/java/movlit/be/pub_sub/notification/NotificationController.java
  be/src/main/java/movlit/be/pub_sub/notification/NotificationMessage.java
  be/src/main/java/movlit/be/pub_sub/notification/SseEmitterService.java
  fe/package-lock.json
  fe/package.json
  fe/src/App.jsx
Labels: feat
